/* Crear un procedimiento almacenado que guarde la información de una nueva toma. Este procedimiento
debe verificar que los valores de las llaves foraneas existan y en caso de existir, se procederá a insertar la nueva toma.
El procedimiento recibirá ocmo parametros los valores que se desean insertar. El procedimiento debe informar o mostrar si se pudo
insertar o no el registro para la nueva toma */

CREATE OR REPLACE PROCEDURE SP_GUARDAR_NUEVA_TOMA (
    P_TOMAID IN TOMAS.TOMAID%TYPE,
    P_HORA IN TOMAS.HORA%TYPE,
    P_FECHA IN TOMAS.FECHA%TYPE,
    P_ANIMALID IN TOMAS.ANIMALID%TYPE,
    P_DIETAID IN TOMAS.DIETAID%TYPE
)

IS
    V_EXISTE NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_EXISTE
    FROM ANIMALXDIETA
    WHERE ANIMALID = P_ANIMALID 
      AND DIETAID = P_DIETAID;

    IF (V_EXISTE > 0) THEN
        INSERT INTO TOMAS (TOMAID, HORA, FECHA, ANIMALID, DIETAID)
        VALUES (P_TOMAID, P_HORA, P_FECHA, P_ANIMALID, P_DIETAID);
        
        DBMS_OUTPUT.PUT_LINE('REGISTRO INSERTADO CORRECTAMENTE.');
        DBMS_OUTPUT.PUT_LINE('TOMA ID: '|| P_TOMAID);
        DBMS_OUTPUT.PUT_LINE('');
    ELSE
        DBMS_OUTPUT.PUT_LINE('NO SE PUDO INSERTAR EL REGISTRO.');
        DBMS_OUTPUT.PUT_LINE('EL ANIMAL (' || P_ANIMALID || ') NO TIENE LA DIETA (' || P_DIETAID || ') ASIGNADA.');
        DBMS_OUTPUT.PUT_LINE('');
    END IF;

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('YA EXISTE UNA TOMA REGISTRADA CON EL ID ' || P_TOMAID);
        DBMS_OUTPUT.PUT_LINE('');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
        DBMS_OUTPUT.PUT_LINE('');
END SP_GUARDAR_NUEVA_TOMA;

SET SERVEROUTPUT ON;

--BLOQUE DE PRUEBA
DECLARE
    V_FECHA DATE := TO_DATE('2026-07-14', 'YYYY-MM-DD');
    V_HORA  TIMESTAMP := TO_TIMESTAMP('2026-07-14 08:30:00', 'YYYY-MM-DD HH24:MI:SS');
BEGIN
    DBMS_OUTPUT.PUT_LINE('INICIO DE PRUEBAS SP_GUARDAR_NUEVA_TOMA');
    
    -- PRUEBA 1: REGISTRO EXITOSO
    DBMS_OUTPUT.PUT_LINE('PRUEBA 1:');
    SP_GUARDAR_NUEVA_TOMA('99', V_HORA, V_FECHA, 'A-01-D1', '134134');

    -- PRUEBA 2: REGISTRO FALLIDO
    DBMS_OUTPUT.PUT_LINE('PRUEBA 2:');
    SP_GUARDAR_NUEVA_TOMA('100', V_HORA, V_FECHA, 'A-01-D1', '342567');
    
    --PRUEBA 3: REGISTRO REPETIDO
    DBMS_OUTPUT.PUT_LINE('PRUEBA 3:');
    SP_GUARDAR_NUEVA_TOMA('99', V_HORA, V_FECHA, 'A-01-D1', '134134');
END;